# TiKV Configuration.

[raftstore]
# set store capacity, if no set, use disk capacity.
capacity = "8G"
pd-heartbeat-tick-interval = "2s"
pd-store-heartbeat-tick-interval = "5s"
split-region-check-tick-interval = "1s"

# 10000000 keys & ~480MB data size in integration tests
[coprocessor]
region-split-size = "10MiB"
region-split-keys = 200000
batch-split-limit = 100

[rocksdb]
max-open-files = 10000

[raftdb]
max-open-files = 10000

[storage]
reserve-space = "0MiB"
enable-ttl = true